#!/usr/bin/env node
/**
 * MT Core Studio - RSS feed generator
 * ---------------------------------------------------------------------
 * Reads data/posts.js and writes feed.xml at the site root.
 *
 * Run after you add or edit a blog post:
 *     node tools/generate-feed.mjs
 *
 * No build step is required to host the site - this is an optional helper
 * that keeps the RSS feed in sync with the posts you write by hand.
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const postsPath = path.join(root, "data", "posts.js");
const configPath = path.join(root, "data", "site-config.js");
const outPath = path.join(root, "feed.xml");

/* ------------------------------ parse posts ------------------------------- */

const rawPosts = readFileSync(postsPath, "utf8");
const marker = "export const posts =";
const start = rawPosts.indexOf(marker);
if (start === -1) {
  console.error('Could not find `export const posts =` in data/posts.js');
  process.exit(1);
}
let jsonPart = rawPosts.slice(start + marker.length).trim().replace(/;\s*$/, "").trim();
jsonPart = jsonPart.replace(/([{,]\s*)([A-Za-z_$][\w$-]*)\s*:/g, '$1"$2":');
jsonPart = jsonPart.replace(/,\s*([}\]])/g, "$1");
const posts = JSON.parse(jsonPart);

/* ------------------------- find the configured domain ---------------------- */

let websiteUrl = "https://example.com";
try {
  const rawConfig = readFileSync(configPath, "utf8");
  const m = rawConfig.match(/websiteUrl\s*:\s*["']([^"']+)["']/);
  if (m && m[1]) websiteUrl = m[1].replace(/\/+$/, "");
} catch {
  /* keep the default */
}

/* --------------------------------- helpers -------------------------------- */

const esc = (value) =>
  String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const rfc822 = (date) => {
  const t = new Date(`${date}T00:00:00Z`);
  return Number.isNaN(t.getTime()) ? String(date) : t.toUTCString();
};

/* -------------------------------- build feed ------------------------------- */

const items = [...posts]
  .sort((a, b) => String(b.date || "").localeCompare(String(a.date || "")))
  .map(
    (post) => `    <item>
      <title>${esc(post.title)}</title>
      <link>${websiteUrl}/blog.html#${esc(post.slug || "")}</link>
      <guid isPermaLink="false">${esc(post.slug || post.title)}</guid>
      <pubDate>${rfc822(post.date)}</pubDate>
      <description>${esc(post.description || "")}</description>
    </item>`
  )
  .join("\n");

const feed = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/generate-feed.mjs - regenerate after editing data/posts.js -->
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>MT Core Studio</title>
    <link>${websiteUrl}/blog.html</link>
    <atom:link href="${websiteUrl}/feed.xml" rel="self" type="application/rss+xml"/>
    <description>News and notes from MT Core Studio, an independent Android app developer.</description>
    <language>en</language>
    <lastBuildDate>${rfc822(new Date().toISOString().slice(0, 10))}</lastBuildDate>
    <generator>MT Core Studio - tools/generate-feed.mjs</generator>
${items}
  </channel>
</rss>
`;

writeFileSync(outPath, feed);
console.log(`Wrote ${outPath} with ${posts.length} item(s).`);